### ISSUE TITLE
Кнопка Edit

### ISSUE THREAD

**Issue by epoletaeva** [arsenty01/Tomatoe#1]
Задизейблить кнопку Edit, если идет таймер (задизейблена кнопка Start).
Добавить всплывающую подсказку при наведении на задизейбленную Edit: "Редактирование настроек доступно только после остановки таймера".

**Comment by arsenty01** [comment]
0.9.2

**Comment by arsenty01** [comment]
NO TOOLTIP

**Comment by arsenty01** [comment]
previous version
