### ISSUE TITLE
Зависание окна

### ISSUE THREAD

**Issue by epoletaeva** [arsenty01/Tomatoe#2]
Плавающая ошибка: Иногда происходит зависание окна при возникновении сообщения о перерыве.

**Comment by epoletaeva** [comment]
![image](https://user-images.githubusercontent.com/29524255/43899546-fbdb1f3e-9bea-11e8-90a9-67d49e8d4658.png)
Опять. попробую не трогать сообщение о перерыве.

**Comment by arsenty01** [comment]
previous version
