### ISSUE TITLE
Зависание

### ISSUE THREAD

**Issue by epoletaeva** [arsenty01/Tomatoe#3]
Странное зависание. Завис таймер.
![image](https://user-images.githubusercontent.com/29524255/43880927-160c7a5c-9bb3-11e8-90cd-4832fe684a0b.png)
Нажала стоп. Затем старт. Завис счетчик таймаута:
![image](https://user-images.githubusercontent.com/29524255/43880936-23eb9572-9bb3-11e8-9487-21d7f1b3212c.png)
Проблема ушла только после повторного открытия программы

**Comment by epoletaeva** [comment]
Снова зависло :(
![image](https://user-images.githubusercontent.com/29524255/43889712-93421c74-9bcd-11e8-8079-f3da0e64cacc.png)

**Comment by epoletaeva** [comment]
Опять :( 
![image](https://user-images.githubusercontent.com/29524255/43895490-2fda640a-9bde-11e8-96cf-c363cd2ac911.png)

**Comment by arsenty01** [comment]
Previous version
